"""add analysis_states table

Revision ID: 993088e694ef
Revises: 48f61799de45
Create Date: 2026-07-12 21:28:26.780911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '993088e694ef'
down_revision: Union[str, Sequence[str], None] = '48f61799de45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('profile', sa.JSON(), nullable=True),
    sa.Column('profile_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('strengths_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suitability', sa.JSON(), nullable=True),
    sa.Column('suitability_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('skill_gap', sa.JSON(), nullable=True),
    sa.Column('skill_gap_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('roadmap', sa.JSON(), nullable=True),
    sa.Column('roadmap_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resume_score', sa.JSON(), nullable=True),
    sa.Column('resume_score_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('recommendations_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_states')
    # ### end Alembic commands ###
